version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  api1:
    build: ./backend
    environment:
      - PORT=4000
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=${MONGODB_URI}
    depends_on: [redis]
  api2:
    build: ./backend
    environment:
      - PORT=4000
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=${MONGODB_URI}
    depends_on: [redis]

  nginx:
    image: nginx:alpine
    depends_on: [api1, api2]
    ports: ["8080:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
